// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller.js"
application.register("accordion", AccordionController)

import AnnouncementsController from "./announcements_controller.js"
application.register("announcements", AnnouncementsController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import ExampleController from "./example_controller.js"
application.register("example", ExampleController)

import FeedController from "./feed_controller.js"
application.register("feed", FeedController)

import FeedUrlController from "./feed_url_controller.js"
application.register("feed-url", FeedUrlController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NavigationController from "./navigation_controller.js"
application.register("navigation", NavigationController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import OpenJobsController from "./open_jobs_controller.js"
application.register("open-jobs", OpenJobsController)

import PreviewController from "./preview_controller.js"
application.register("preview", PreviewController)

import Sjabloon__CouponController from "./sjabloon/coupon_controller.js"
application.register("sjabloon--coupon", Sjabloon__CouponController)

import Sjabloon__PlanSwitchController from "./sjabloon/plan_switch_controller.js"
application.register("sjabloon--plan-switch", Sjabloon__PlanSwitchController)

import Sjabloon__StripeController from "./sjabloon/stripe_controller.js"
application.register("sjabloon--stripe", Sjabloon__StripeController)

import Sjabloon__ToggleController from "./sjabloon/toggle_controller.js"
application.register("sjabloon--toggle", Sjabloon__ToggleController)

import TabsController from "./tabs_controller.js"
application.register("tabs", TabsController)
