version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          RAILS_ENV: test
          POSTGRESQL_HOST: 127.0.0.1

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: rssmailer
          POSTGRES_PASSWORD: rssmailer
          POSTGRES_DB: rssmailer

    working_directory: ~/rssmailer-app

    steps:
      - run:
          name: Update bundler 2
          command: gem install bundler:2.2.27
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          keys:
            - v2-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
            - v2-gem-cache-{{ arch }}-
            - v2-gem-cache-{{ arch }}


      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - vendor/bundle
          key: v2-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create database
          command: RAILS_ENV=test bin/rake db:create db:schema:load

      - run:
          name: Migrate database
          command: RAILS_ENV=test bin/rake db:migrate

      - run:
          name: Run unit tests
          command: bundle exec rails test

      - run:
          name: Run system tests
          command: bundle exec rails test:system


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build